# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run carthage bootstrap"
  lane :carthage_bootstrap do
    carthage(
      command: "bootstrap",
      verbose: true,
      cache_builds: true,
      platform: 'iOS',
      use_binaries: false,
    )
  end

  desc "Build app"
  lane :build do
    build_app(scheme: 'BookStore')
  end

  lane :ui_tests do
    run_tests(scheme: "BookStoreKit")
  end

  lane :unit_tests do
    run_tests(scheme: "BookStore")
  end

  lane :networking_tests do
    run_tests(scheme: "Networking")
  end

  lane :test do
    carthage_bootstrap()
    unit_tests()
    networking_tests()
    ui_tests()
  end
end
