on: [workflow_dispatch]

jobs:
  test-build-ios:
    runs-on: [self-hosted, macos, gala]
    name: Test and Build iOS App
    steps:
      - name: Test and Build
        run: |
          pwd
          ls
          fastlane test_build
